 
appName: cartservice 
appReplicas: 1

appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.6.0

containerPort: 7070
servicePort: 7070

containerVars:
- name: PORT 
  value: "7070"
- name: REDIS_ADDR
  value: "redis-cart:6379"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
serviceType: ClusterIP