 
appName: checkoutservice 
appReplicas: 1

appImage: gcr.io/google-samples/microservices-demo/checkoutservice
appVersion: v0.6.0

containerPort: 5050
servicePort: 5050

containerVars:
- name: PORT
  value: "5050"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: "CART_SERVICE_ADDR"
  value: "cartservice:7070"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
serviceType: ClusterIP