 
appName: emailservice 
appReplicas: 1

appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.6.0

containerPort: 8080
servicePort: 5000

containerVars:
- name: PORT 
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"

serviceType: ClusterIP