 
appName: productcatalogservice 
appReplicas: 1

appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.6.0

containerPort: 3550
servicePort: 3550

containerVars:
- name: PORT
  value: "3550"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"

serviceType: ClusterIP