 
appName: shippingservice 
appReplicas: 1

appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.6.0

containerPort: 50051
servicePort: 50051

containerVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"

serviceType: ClusterIP