apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
      
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: PORT 
            value: "8080"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
          
---

apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  ports:
  - port: 5000
    targetPort: 8080

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
    targetPort: 8080

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3550
        env:
          - name: PORT
            value: "3550"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  ports:
  - port: 3550
    targetPort: 3550

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
          


---

apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
  - port: 50051
    targetPort: 50051

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 7000
        env:
          - name: PORT 
            value: "7000"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
  - port: 7000
    targetPort: 7000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 50051
        env:
          - name: PORT 
            value: "50051"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051

---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: gcr.io/google-samples/microservices-demo/adservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 9555
        env:
          - name: PORT 
            value: "9555"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi

---

apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app: adservice
  ports:
  - port: 9555
    targetPort: 9555

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 7070
        env:
          - name: PORT 
            value: "7070"
          - name: REDIS_ADDR
            value: "redis-cart:6379"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis-cart
        image: redis:alpine
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          tcpSocket:
            port: 6379
        readinessProbe: 
          periodSeconds: 5
          initialDelaySeconds: 5
          tcpSocket:
            port: 6379
        resources:
          requests:
            cpu: 70m
            memory: 200Mi
          limits:
            cpu: 125m
            memory: 300Mi
      volumes:
        - name: redis-data
          emptyDir: {}
      

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  selector:
    app: redis-cart
  ports:
  - port: 6379
    targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5050
        env:
          - name: PORT
            value: "5050"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: "CART_SERVICE_ADDR"
            value: "cartservice:7070"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:5000"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
  - port: 5050
    targetPort: 5050


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice
spec:
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
      - name: frontendservice
        image: gcr.io/google-samples/microservices-demo/frontend:v0.6.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"

          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"

          - name: "CART_SERVICE_ADDR"
            value: "cartservice:7070"

          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice:8080"

          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"

          - name: "CHECKOUT_SERVICE_ADDR"
            value: "checkoutservice:5050"

          - name: AD_SERVICE_ADDR
            value: "adservice:9555"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          initialDelaySeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        # readinessProbe:
        #   periodSeconds: 5
        #   initialDelaySeconds: 5
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: frontendservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    # nodePort: 30080
  # type: NodePort





---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: mithun.tutorial.one@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"

spec:
  # ingressClassName: nginx
  tls:
    - hosts:
      - mithunhalder.com
      secretName: mithunhalder.com-tls
  rules:
    - host: mithunhalder.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: frontendservice
                port:
                  number: 80
            path: /